name: Rust-Checker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - name: cache rust project
        uses: Swatinem/rust-cache@v2
      - name: Build the binaries
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
